# Generated by Django 4.2.30 on 2026-05-23 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='effort',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (6, '6'), (8, '8'), (10, '10'), (20, '20')], default=1),
        ),
        migrations.AddField(
            model_name='userstory',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En desarrollo', 'En desarrollo'), ('Concluida', 'Concluida')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='userstory',
            name='value',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10),
        ),
        migrations.CreateModel(
            name='UserStoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrum.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptanceCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='scrum.userstory')),
            ],
        ),
    ]
