# Generated by Django 4.2.30 on 2026-06-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_remove_sprint_is_active_sprint_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='project_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
