# Generated by Django 4.2.30 on 2026-05-23 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrum', '0002_userstory_effort_userstory_status_userstory_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='is_active',
        ),
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('Planeado', 'Planeado'), ('Activo', 'Activo'), ('Cerrado', 'Cerrado')], default='Planeado', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='scrum.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='effort',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (6, '6'), (8, '8'), (10, '10'), (20, '20')], default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Feature', 'Feature'), ('Artefacto', 'Artefacto'), ('Spike', 'Spike [Research]'), ('Task', 'Task')], default='Task', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='value',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('Ready', 'Ready'), ('Doing', 'Doing'), ('Blocked', 'Blocked'), ('Review', 'Review'), ('Testing', 'Testing'), ('Done', 'Done')], default='Backlog', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketAcceptanceCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='scrum.ticket')),
            ],
        ),
    ]
